# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export.ui',
# licensing of 'export.ui' applies.
#
# Created: Sun Jan  5 18:04:20 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ExportDialog(object):
    def setupUi(self, ExportDialog):
        ExportDialog.setObjectName("ExportDialog")
        ExportDialog.resize(650, 560)
        ExportDialog.setMinimumSize(QtCore.QSize(650, 560))
        ExportDialog.setMaximumSize(QtCore.QSize(650, 560))
        self.buttonBox = QtWidgets.QDialogButtonBox(ExportDialog)
        self.buttonBox.setGeometry(QtCore.QRect(300, 520, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.characterBox = QtWidgets.QListWidget(ExportDialog)
        self.characterBox.setGeometry(QtCore.QRect(10, 30, 256, 211))
        self.characterBox.setObjectName("characterBox")
        self.label = QtWidgets.QLabel(ExportDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 18))
        self.label.setObjectName("label")
        self.directoryBox = QtWidgets.QComboBox(ExportDialog)
        self.directoryBox.setGeometry(QtCore.QRect(300, 130, 341, 32))
        self.directoryBox.setObjectName("directoryBox")
        self.directoryBox.addItem("")
        self.directoryBox.addItem("")
        self.directoryBox.addItem("")
        self.label_2 = QtWidgets.QLabel(ExportDialog)
        self.label_2.setGeometry(QtCore.QRect(310, 110, 141, 18))
        self.label_2.setObjectName("label_2")
        self.selectCharacterButton = QtWidgets.QPushButton(ExportDialog)
        self.selectCharacterButton.setGeometry(QtCore.QRect(70, 250, 191, 34))
        self.selectCharacterButton.setObjectName("selectCharacterButton")
        self.fileNameBox = QtWidgets.QLineEdit(ExportDialog)
        self.fileNameBox.setGeometry(QtCore.QRect(300, 30, 341, 32))
        self.fileNameBox.setObjectName("fileNameBox")
        self.label_3 = QtWidgets.QLabel(ExportDialog)
        self.label_3.setGeometry(QtCore.QRect(310, 10, 81, 18))
        self.label_3.setObjectName("label_3")
        self.namePreview = QtWidgets.QLabel(ExportDialog)
        self.namePreview.setGeometry(QtCore.QRect(300, 70, 341, 41))
        self.namePreview.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.namePreview.setWordWrap(True)
        self.namePreview.setObjectName("namePreview")
        self.formatBox = QtWidgets.QComboBox(ExportDialog)
        self.formatBox.setGeometry(QtCore.QRect(300, 190, 81, 32))
        self.formatBox.setObjectName("formatBox")
        self.formatBox.addItem("")
        self.formatBox.addItem("")
        self.formatBox.addItem("")
        self.sampleBox = QtWidgets.QSpinBox(ExportDialog)
        self.sampleBox.setGeometry(QtCore.QRect(400, 190, 81, 32))
        self.sampleBox.setMinimum(1)
        self.sampleBox.setMaximum(999999)
        self.sampleBox.setProperty("value", 48000)
        self.sampleBox.setObjectName("sampleBox")
        self.label_5 = QtWidgets.QLabel(ExportDialog)
        self.label_5.setGeometry(QtCore.QRect(310, 170, 91, 18))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(ExportDialog)
        self.label_6.setGeometry(QtCore.QRect(410, 170, 81, 18))
        self.label_6.setObjectName("label_6")
        self.moodBox = QtWidgets.QListWidget(ExportDialog)
        self.moodBox.setGeometry(QtCore.QRect(10, 300, 256, 211))
        self.moodBox.setObjectName("moodBox")
        self.selectMoodButton = QtWidgets.QPushButton(ExportDialog)
        self.selectMoodButton.setGeometry(QtCore.QRect(90, 520, 171, 34))
        self.selectMoodButton.setObjectName("selectMoodButton")
        self.label_7 = QtWidgets.QLabel(ExportDialog)
        self.label_7.setGeometry(QtCore.QRect(20, 280, 71, 18))
        self.label_7.setObjectName("label_7")
        self.metadataBox = QtWidgets.QComboBox(ExportDialog)
        self.metadataBox.setGeometry(QtCore.QRect(300, 250, 341, 32))
        self.metadataBox.setObjectName("metadataBox")
        self.metadataBox.addItem("")
        self.metadataBox.addItem("")
        self.metadataBox.addItem("")
        self.label_8 = QtWidgets.QLabel(ExportDialog)
        self.label_8.setGeometry(QtCore.QRect(310, 230, 131, 18))
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(ExportDialog)
        self.line.setGeometry(QtCore.QRect(270, 10, 31, 541))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_9 = QtWidgets.QLabel(ExportDialog)
        self.label_9.setGeometry(QtCore.QRect(310, 350, 161, 21))
        self.label_9.setObjectName("label_9")
        self.reservedBox = QtWidgets.QCheckBox(ExportDialog)
        self.reservedBox.setGeometry(QtCore.QRect(300, 380, 331, 22))
        self.reservedBox.setChecked(True)
        self.reservedBox.setObjectName("reservedBox")
        self.spaceBox = QtWidgets.QCheckBox(ExportDialog)
        self.spaceBox.setGeometry(QtCore.QRect(300, 410, 331, 22))
        self.spaceBox.setObjectName("spaceBox")
        self.bitDepthBox = QtWidgets.QComboBox(ExportDialog)
        self.bitDepthBox.setGeometry(QtCore.QRect(500, 190, 81, 32))
        self.bitDepthBox.setObjectName("bitDepthBox")
        self.bitDepthBox.addItem("")
        self.bitDepthBox.addItem("")
        self.bitDepthBox.addItem("")
        self.label_10 = QtWidgets.QLabel(ExportDialog)
        self.label_10.setGeometry(QtCore.QRect(510, 170, 81, 18))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(ExportDialog)
        self.label_11.setGeometry(QtCore.QRect(310, 290, 161, 21))
        self.label_11.setObjectName("label_11")
        self.noise0Box = QtWidgets.QCheckBox(ExportDialog)
        self.noise0Box.setGeometry(QtCore.QRect(300, 320, 87, 22))
        self.noise0Box.setChecked(True)
        self.noise0Box.setObjectName("noise0Box")
        self.noise1Box = QtWidgets.QCheckBox(ExportDialog)
        self.noise1Box.setGeometry(QtCore.QRect(390, 320, 87, 22))
        self.noise1Box.setChecked(True)
        self.noise1Box.setObjectName("noise1Box")
        self.noise2Box = QtWidgets.QCheckBox(ExportDialog)
        self.noise2Box.setGeometry(QtCore.QRect(480, 320, 87, 22))
        self.noise2Box.setChecked(True)
        self.noise2Box.setObjectName("noise2Box")

        self.retranslateUi(ExportDialog)
        self.directoryBox.setCurrentIndex(1)
        self.formatBox.setCurrentIndex(0)
        self.metadataBox.setCurrentIndex(0)
        self.bitDepthBox.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ExportDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ExportDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ExportDialog)
        ExportDialog.setTabOrder(self.characterBox, self.selectCharacterButton)
        ExportDialog.setTabOrder(self.selectCharacterButton, self.moodBox)
        ExportDialog.setTabOrder(self.moodBox, self.selectMoodButton)
        ExportDialog.setTabOrder(self.selectMoodButton, self.fileNameBox)
        ExportDialog.setTabOrder(self.fileNameBox, self.directoryBox)
        ExportDialog.setTabOrder(self.directoryBox, self.formatBox)
        ExportDialog.setTabOrder(self.formatBox, self.sampleBox)
        ExportDialog.setTabOrder(self.sampleBox, self.bitDepthBox)
        ExportDialog.setTabOrder(self.bitDepthBox, self.metadataBox)
        ExportDialog.setTabOrder(self.metadataBox, self.noise0Box)
        ExportDialog.setTabOrder(self.noise0Box, self.noise1Box)
        ExportDialog.setTabOrder(self.noise1Box, self.noise2Box)
        ExportDialog.setTabOrder(self.noise2Box, self.reservedBox)
        ExportDialog.setTabOrder(self.reservedBox, self.spaceBox)

    def retranslateUi(self, ExportDialog):
        ExportDialog.setWindowTitle(QtWidgets.QApplication.translate("ExportDialog", "Export dataset", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("ExportDialog", "Characters", None, -1))
        self.directoryBox.setItemText(0, QtWidgets.QApplication.translate("ExportDialog", "Single directory", None, -1))
        self.directoryBox.setItemText(1, QtWidgets.QApplication.translate("ExportDialog", "Separate by episode", None, -1))
        self.directoryBox.setItemText(2, QtWidgets.QApplication.translate("ExportDialog", "Separate by character", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("ExportDialog", "Directory options", None, -1))
        self.selectCharacterButton.setText(QtWidgets.QApplication.translate("ExportDialog", "Select/Deselect all characters", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("ExportDialog", "File names", None, -1))
        self.namePreview.setText(QtWidgets.QApplication.translate("ExportDialog", "Preview: ", None, -1))
        self.formatBox.setItemText(0, QtWidgets.QApplication.translate("ExportDialog", "FLAC", None, -1))
        self.formatBox.setItemText(1, QtWidgets.QApplication.translate("ExportDialog", "WAV", None, -1))
        self.formatBox.setItemText(2, QtWidgets.QApplication.translate("ExportDialog", "RAW", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("ExportDialog", "File format", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("ExportDialog", "Sample rate", None, -1))
        self.selectMoodButton.setText(QtWidgets.QApplication.translate("ExportDialog", "Select/Deselect all moods", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("ExportDialog", "Moods", None, -1))
        self.metadataBox.setItemText(0, QtWidgets.QApplication.translate("ExportDialog", "TXT files", None, -1))
        self.metadataBox.setItemText(1, QtWidgets.QApplication.translate("ExportDialog", "JSON array", None, -1))
        self.metadataBox.setItemText(2, QtWidgets.QApplication.translate("ExportDialog", "LJSpeech", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("ExportDialog", "Metadata format", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("ExportDialog", "Additional options", None, -1))
        self.reservedBox.setText(QtWidgets.QApplication.translate("ExportDialog", "Remove reserved characters from file names", None, -1))
        self.spaceBox.setText(QtWidgets.QApplication.translate("ExportDialog", "Remove spaces from file names", None, -1))
        self.bitDepthBox.setItemText(0, QtWidgets.QApplication.translate("ExportDialog", "8-bit", None, -1))
        self.bitDepthBox.setItemText(1, QtWidgets.QApplication.translate("ExportDialog", "16-bit", None, -1))
        self.bitDepthBox.setItemText(2, QtWidgets.QApplication.translate("ExportDialog", "24-bit", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("ExportDialog", "Bit depth", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("ExportDialog", "Noise levels", None, -1))
        self.noise0Box.setText(QtWidgets.QApplication.translate("ExportDialog", "Clean", None, -1))
        self.noise1Box.setText(QtWidgets.QApplication.translate("ExportDialog", "Noisy", None, -1))
        self.noise2Box.setText(QtWidgets.QApplication.translate("ExportDialog", "Very noisy", None, -1))

